# Generated by Django 4.2.4 on 2023-08-14 05:31

import api.models.employee_model
import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='logo',
            field=models.ImageField(blank=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to=api.models.employee_model.employee_avatar_upload_to, verbose_name='Avatar'),
        ),
    ]
