# Generated by Django 4.2.4 on 2023-08-14 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_employee_logo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='logo',
            new_name='avatar',
        ),
    ]
