# Generated by Django 4.2.4 on 2023-08-04 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_myuser_managers_alter_myuser_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='username',
        ),
    ]
