# Generated by Django 4.2.4 on 2023-08-17 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_employment_employee_alter_employment_job_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='job_roles',
            field=models.ManyToManyField(related_name='employees', through='api.Employment', to='api.jobrole', verbose_name='Job Roles'),
        ),
    ]
