# Generated by Django 4.2.4 on 2023-08-04 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_myuser_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Company Name')),
                ('motto', models.CharField(max_length=250, verbose_name='Company Motto')),
                ('description', models.CharField(blank=True, max_length=5000, verbose_name='Company Description')),
                ('website', models.URLField(verbose_name='Company Website')),
                ('hq_address', models.CharField(max_length=500, verbose_name='Company HQ Address')),
            ],
        ),
    ]
