# Generated by Django 4.2.4 on 2023-08-04 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_company'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name_plural': 'companies'},
        ),
        migrations.AlterField(
            model_name='company',
            name='description',
            field=models.TextField(blank=True, max_length=5000, verbose_name='Company Description'),
        ),
        migrations.AlterField(
            model_name='company',
            name='hq_address',
            field=models.CharField(blank=True, max_length=500, verbose_name='Company HQ Address'),
        ),
        migrations.AlterField(
            model_name='company',
            name='motto',
            field=models.CharField(blank=True, max_length=250, verbose_name='Company Motto'),
        ),
        migrations.AlterField(
            model_name='company',
            name='website',
            field=models.URLField(blank=True, verbose_name='Company Website'),
        ),
    ]
