# Generated by Django 4.2.4 on 2023-08-14 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_department_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobrole',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_roles', to='api.department', verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='jobrole',
            name='description',
            field=models.TextField(blank=True, max_length=5000, verbose_name='Job Role Description'),
        ),
    ]
