# Generated by Django 4.2.4 on 2023-08-17 22:27

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_employment_salary_employment_salary_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employment',
            name='salary',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=4, default_currency='USD', max_digits=19, null=True, verbose_name='salary'),
        ),
    ]
