# Generated by Django 4.2.4 on 2023-08-14 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_jobrole_department_alter_jobrole_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobrole',
            options={'verbose_name': 'Job Role'},
        ),
    ]
