# Generated by Django 4.2.4 on 2023-08-04 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_company_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='hq_address',
            field=models.TextField(blank=True, max_length=500, verbose_name='Company HQ Address'),
        ),
    ]
