# Generated by Django 4.2.4 on 2023-08-18 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_jobposting_job_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposting',
            name='job_role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_postings', to='api.jobrole', verbose_name='Job Role'),
        ),
    ]
