# Generated by Django 4.2.4 on 2023-08-18 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_jobposting_job_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobposting',
            options={'verbose_name_plural': 'Job Postings'},
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='job_role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_postings', to='api.jobrole', verbose_name='Job Role'),
        ),
    ]
