# Generated by Django 4.2.4 on 2023-08-04 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Job Role Name')),
                ('description', models.TextField(blank=True, max_length=500, verbose_name='Job Role Description')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.department', verbose_name='Department')),
            ],
        ),
    ]
