# Generated by Django 4.2.4 on 2023-08-04 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_jobrole'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('employment_type', models.CharField(choices=[('FT', 'Full-Time'), ('PT', 'Part-Time'), ('IS', 'Internship')], max_length=2, verbose_name='Employment Type')),
                ('is_remote', models.BooleanField(verbose_name='Is Remote')),
                ('salary_frequency', models.CharField(choices=[('H', 'Hourly'), ('D', 'Daily'), ('W', 'Weekly'), ('B', 'Bi-weekly'), ('M', 'Monthly')], max_length=1, verbose_name='Salary Frequency')),
                ('salary_amount', models.DecimalField(decimal_places=4, max_digits=20, verbose_name='Salary Amount')),
                ('note', models.CharField(max_length=150, verbose_name='Employment Note')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.employee', verbose_name='Employee')),
                ('job_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.jobrole', verbose_name='Job Role')),
            ],
        ),
    ]
