# Generated by Django 4.2.4 on 2023-08-18 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_jobposting_options_alter_jobposting_job_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobpostingsalary',
            name='id',
        ),
        migrations.AlterField(
            model_name='jobpostingsalary',
            name='job_posting',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='job_posting_salary', serialize=False, to='api.jobposting', verbose_name='Job Posting'),
        ),
    ]
