# Generated by Django 4.2.4 on 2023-08-04 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_employment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employment',
            name='note',
            field=models.CharField(blank=True, max_length=150, verbose_name='Employment Note'),
        ),
    ]
