# Generated by Django 4.2.4 on 2023-08-18 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_jobpostingsalary_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JobPostingSalary',
        ),
    ]
