# Generated by Django 4.2.4 on 2023-08-18 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_delete_jobpostingsalary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='job_posting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicants', to='api.jobposting', verbose_name='Job Posting'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='status',
            field=models.CharField(blank=True, choices=[('A', 'Applied'), ('Q', 'Qualified'), ('I', 'Interviewing'), ('S', 'Short-listed'), ('O', 'Offered'), ('H', 'Hired'), ('R', 'Rejected'), ('D', 'Denied')], default='A', max_length=1, verbose_name='Status'),
        ),
    ]
