# Generated by Django 4.2.4 on 2023-08-18 12:22

import api.models.applicant_model
import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_applicant_email_alter_applicant_job_posting_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='resume',
            field=models.FileField(blank=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to=api.models.applicant_model.applicant_resume_upload_to, verbose_name='Resume'),
        ),
    ]
