# Generated by Django 4.2.4 on 2023-08-18 13:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_applicant_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='applied_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Applied At'),
        ),
    ]
