# Generated by Django 4.2.4 on 2023-08-05 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_employment_salary_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='country',
        ),
        migrations.RemoveField(
            model_name='company',
            name='hq_address',
        ),
        migrations.AddField(
            model_name='company',
            name='address',
            field=models.TextField(blank=True, max_length=500, verbose_name='Company Address'),
        ),
    ]
