# Generated by Django 4.2.4 on 2023-08-18 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_applicant_applied_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='api.employee', verbose_name='Employee')),
                ('job_posting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='api.jobposting', verbose_name='Job Posting')),
            ],
        ),
        migrations.AddField(
            model_name='jobposting',
            name='interviewers',
            field=models.ManyToManyField(related_name='job_postings', through='api.Interview', to='api.employee', verbose_name='Interviewers'),
        ),
        migrations.AlterField(
            model_name='interviewresult',
            name='interviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.interview', verbose_name='Interviewer'),
        ),
        migrations.DeleteModel(
            name='Interviewer',
        ),
    ]
