# Generated by Django 4.2.4 on 2023-08-05 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_remove_company_country_remove_company_hq_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='website',
            field=models.CharField(blank=True, max_length=50, verbose_name='Company Website'),
        ),
    ]
