# Generated by Django 4.2.4 on 2023-08-18 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_interview_jobposting_interviewers_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Interview',
            new_name='Interviewer',
        ),
    ]
