# Generated by Django 4.2.4 on 2023-08-18 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_rename_interview_interviewer'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='interviewer',
            unique_together={('job_posting', 'employee')},
        ),
    ]
