# Generated by Django 4.2.4 on 2023-08-18 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_interviewer_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobposting',
            old_name='interviewers',
            new_name='interviewer_employees',
        ),
        migrations.AlterField(
            model_name='interviewer',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.employee', verbose_name='Employee'),
        ),
        migrations.AlterField(
            model_name='interviewer',
            name='job_posting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviewers', to='api.jobposting', verbose_name='Job Posting'),
        ),
    ]
