# Generated by Django 4.2.4 on 2023-08-18 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_rename_interviewers_jobposting_interviewer_employees_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='interviewers',
            field=models.ManyToManyField(related_name='applicants', through='api.InterviewResult', to='api.interviewer', verbose_name='Interviewers'),
        ),
        migrations.AlterField(
            model_name='interviewresult',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_results', to='api.applicant', verbose_name='Applicant'),
        ),
        migrations.AlterField(
            model_name='interviewresult',
            name='interviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_results', to='api.interviewer', verbose_name='Interviewer'),
        ),
    ]
