# Generated by Django 4.2.4 on 2023-08-05 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_employee_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_owner',
            field=models.BooleanField(default=False, verbose_name='Is Owner'),
        ),
    ]
