# Generated by Django 4.2.4 on 2023-08-18 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_applicant_interviewers_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='interviewresult',
            unique_together={('applicant', 'interviewer')},
        ),
    ]
