# Generated by Django 4.2.4 on 2023-09-03 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_alter_interviewresult_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewresult',
            name='score',
            field=models.FloatField(blank=True, null=True, verbose_name='Interview Score'),
        ),
        migrations.AlterField(
            model_name='timeoff',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_offs', to='api.employee', verbose_name='Employee'),
        ),
    ]
