# Generated by Django 4.2.4 on 2023-09-04 08:05

import api.models.company_model
import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_alter_tracking_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to=api.models.company_model.company_logo_upload_to, verbose_name='Company Logo'),
        ),
    ]
