# Generated by Django 4.2.4 on 2023-09-10 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_alter_company_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tracking',
            name='note',
        ),
        migrations.AddField(
            model_name='tracking',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
    ]
