# PUll base image
FROM python:3.11.4-slim-buster

# Set work directory
WORKDIR /usr/src/backend

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Install system dependencies
RUN apt-get update && apt-get install -y netcat

# Install Python dependencies
RUN pip install --upgrade pip
COPY ./requirements.txt .
RUN pip install -r requirements.txt

# Copy entrypoint.dev.sh
COPY ./entrypoint.dev.sh .
RUN sed -i 's/\r$//g' /usr/src/backend/entrypoint.dev.sh
RUN chmod +x /usr/src/backend/entrypoint.dev.sh

# Copy project
COPY . .

# Run entrypoint.dev.sh
ENTRYPOINT ["./entrypoint.dev.sh"]
